function ca(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ca(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=da(this);function q(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&l(c,a,{configurable:!0,writable:!0,value:b})}}
function t(){this.G=!1;this.B=null;this.C=void 0;this.v=1;this.J=this.F=0;this.D=null}function u(a){if(a.G)throw new TypeError("Generator is already running");a.G=!0}t.prototype.H=function(a){this.C=a};function v(a,b){a.D={T:b,ea:!0};a.v=a.F||a.J}t.prototype.return=function(a){this.D={return:a};this.v=this.J};function w(a,b,c){a.v=c;return{value:b}}function y(a){a.F=0;var b=a.D.T;a.D=null;return b}function ea(a){this.v=new t;this.B=a}
function fa(a,b){u(a.v);var c=a.v.B;if(c)return z(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.v.return);a.v.return(b);return A(a)}function z(a,b,c,d){try{var e=b.call(a.v.B,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.v.G=!1,e;var h=e.value}catch(f){return a.v.B=null,v(a.v,f),A(a)}a.v.B=null;d.call(a.v,h);return A(a)}
function A(a){for(;a.v.v;)try{var b=a.B(a.v);if(b)return a.v.G=!1,{value:b.value,done:!1}}catch(c){a.v.C=void 0,v(a.v,c)}a.v.G=!1;if(a.v.D){b=a.v.D;a.v.D=null;if(b.ea)throw b.T;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ha(a){this.next=function(b){u(a.v);a.v.B?b=z(a,a.v.B.next,b,a.v.H):(a.v.H(b),b=A(a));return b};this.throw=function(b){u(a.v);a.v.B?b=z(a,a.v.B["throw"],b,a.v.H):(v(a.v,b),b=A(a));return b};this.return=function(b){return fa(a,b)};this[Symbol.iterator]=function(){return this}}function ia(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}
function D(a){return ia(new ha(new ea(a)))}q("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.v=h;l(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.v};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ja(ca(this))}})}return a});function ja(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
q("Promise",function(a){function b(f){this.B=0;this.C=void 0;this.v=[];this.H=!1;var k=this.D();try{f(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.v=null}function d(f){return f instanceof b?f:new b(function(k){k(f)})}if(a)return a;c.prototype.B=function(f){if(null==this.v){this.v=[];var k=this;this.C(function(){k.F()})}this.v.push(f)};var e=n.setTimeout;c.prototype.C=function(f){e(f,0)};c.prototype.F=function(){for(;this.v&&this.v.length;){var f=this.v;this.v=[];for(var k=0;k<f.length;++k){var m=
f[k];f[k]=null;try{m()}catch(p){this.D(p)}}}this.v=null};c.prototype.D=function(f){this.C(function(){throw f;})};b.prototype.D=function(){function f(p){return function(r){m||(m=!0,p.call(k,r))}}var k=this,m=!1;return{resolve:f(this.Y),reject:f(this.F)}};b.prototype.Y=function(f){if(f===this)this.F(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.$(f);else{a:switch(typeof f){case "object":var k=null!=f;break a;case "function":k=!0;break a;default:k=!1}k?this.X(f):this.G(f)}};
b.prototype.X=function(f){var k=void 0;try{k=f.then}catch(m){this.F(m);return}"function"==typeof k?this.aa(k,f):this.G(f)};b.prototype.F=function(f){this.J(2,f)};b.prototype.G=function(f){this.J(1,f)};b.prototype.J=function(f,k){if(0!=this.B)throw Error("Cannot settle("+f+", "+k+"): Promise already settled in state"+this.B);this.B=f;this.C=k;2===this.B&&this.Z();this.V()};b.prototype.Z=function(){var f=this;e(function(){if(f.W()){var k=n.console;"undefined"!==typeof k&&k.error(f.C)}},1)};b.prototype.W=
function(){if(this.H)return!1;var f=n.CustomEvent,k=n.Event,m=n.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof k?f=new k("unhandledrejection",{cancelable:!0}):(f=n.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.C;return m(f)};b.prototype.V=function(){if(null!=this.v){for(var f=0;f<this.v.length;++f)h.B(this.v[f]);this.v=null}};var h=new c;b.prototype.$=
function(f){var k=this.D();f.N(k.resolve,k.reject)};b.prototype.aa=function(f,k){var m=this.D();try{f.call(k,m.resolve,m.reject)}catch(p){m.reject(p)}};b.prototype.then=function(f,k){function m(x,B){return"function"==typeof x?function(aa){try{p(x(aa))}catch(ba){r(ba)}}:B}var p,r,C=new b(function(x,B){p=x;r=B});this.N(m(f,p),m(k,r));return C};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.N=function(f,k){function m(){switch(p.B){case 1:f(p.C);break;case 2:k(p.C);break;default:throw Error("Unexpected state: "+
p.B);}}var p=this;null==this.v?h.B(m):this.v.push(m);this.H=!0};b.resolve=d;b.reject=function(f){return new b(function(k,m){m(f)})};b.race=function(f){return new b(function(k,m){for(var p=g(f),r=p.next();!r.done;r=p.next())d(r.value).N(k,m)})};b.all=function(f){var k=g(f),m=k.next();return m.done?d([]):new b(function(p,r){function C(aa){return function(ba){x[aa]=ba;B--;0==B&&p(x)}}var x=[],B=0;do x.push(void 0),B++,d(m.value).N(C(x.length-1),r),m=k.next();while(!m.done)})};return b});
q("globalThis",function(a){return a||n});function ka(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
q("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ka(this,b,"startsWith"),e=d.length,h=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<h&&c<e;)if(d[c++]!=b[f++])return!1;return f>=h}});q("String.prototype.codePointAt",function(a){return a?a:function(b){var c=ka(this,null,"codePointAt"),d=c.length;b=Number(b)||0;if(0<=b&&b<d){b|=0;var e=c.charCodeAt(b);if(55296>e||56319<e||b+1===d)return e;b=c.charCodeAt(b+1);return 56320>b||57343<b?e:1024*(e-55296)+b+9216}}});
function la(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.keys",function(a){return a?a:function(){return la(this,function(b){return b})}});
q("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});function E(a){return a?a:Array.prototype.fill}q("Int8Array.prototype.fill",E);q("Uint8Array.prototype.fill",E);q("Uint8ClampedArray.prototype.fill",E);q("Int16Array.prototype.fill",E);q("Uint16Array.prototype.fill",E);q("Int32Array.prototype.fill",E);
q("Uint32Array.prototype.fill",E);q("Float32Array.prototype.fill",E);q("Float64Array.prototype.fill",E);var F;F||(F=typeof Module != 'undefined' ? Module : {});var ma=!!globalThis.window,na=!!globalThis.WorkerGlobalScope,oa,pa,qa,ra=(null==(oa=globalThis.process)?void 0:null==(pa=oa.versions)?void 0:pa.node)&&"renderer"!=(null==(qa=globalThis.process)?void 0:qa.type),sa,ta,ua=null==(sa=globalThis.document)?void 0:null==(ta=sa.currentScript)?void 0:ta.src;
"undefined"!=typeof __filename?ua=__filename:na&&(ua=self.location.href);var G="",va,H;
if(ra){var fs=require("fs");G=__dirname+"/";H=function(a){a=I(a)?new URL(a):a;return fs.readFileSync(a)};va=function(a){var b=void 0===b?!0:b;var c;return D(function(d){a=I(a)?new URL(a):a;c=fs.readFileSync(a,b?void 0:"utf8");return d.return(c)})};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=F)}else if(ma||na){try{G=(new URL(".",ua)).href}catch(a){}na&&(H=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
va=function(a){var b;return D(function(c){if(1==c.v)return I(a)?c.return(new Promise(function(d,e){var h=new XMLHttpRequest;h.open("GET",a,!0);h.responseType="arraybuffer";h.onload=function(){200==h.status||0==h.status&&h.response?d(h.response):e(h.status)};h.onerror=e;h.send(null)})):w(c,fetch(a,{credentials:"same-origin"}),2);b=c.C;if(b.ok)return c.return(b.arrayBuffer());throw Error(b.status+" : "+b.url);})}}var wa=console.log.bind(console),J=console.error.bind(console),K,xa=!1;
function I(a){return a.startsWith("file://")}var ya,L,M;function za(){var a=N.buffer;ya=new Int8Array(a);new Int16Array(a);L=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);M=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function O(a){var b,c;null==(c=(b=F).onAbort)||c.call(b,a);a="Aborted("+a+")";J(a);xa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var P;
function Aa(a){var b;return D(function(c){switch(c.v){case 1:if(K){c.v=2;break}c.F=3;return w(c,va(a),5);case 5:return b=c.C,c.return(new Uint8Array(b));case 3:y(c);case 2:var d=c.return;if(a==P&&K)var e=new Uint8Array(K);else if(H)e=H(a);else throw"both async and sync fetching of the wasm failed";return d.call(c,e)}})}
function Ba(a,b){var c,d,e;return D(function(h){switch(h.v){case 1:return h.F=2,w(h,Aa(a),4);case 4:return c=h.C,w(h,WebAssembly.instantiate(c,b),5);case 5:return d=h.C,h.return(d);case 2:e=y(h),J("failed to asynchronously prepare wasm: "+e),O(e),h.v=0}})}
function Ca(a){var b=K,c=P,d,e,h;return D(function(f){switch(f.v){case 1:if(b||I(c)||ra){f.v=2;break}f.F=3;d=fetch(c,{credentials:"same-origin"});return w(f,WebAssembly.instantiateStreaming(d,a),5);case 5:return e=f.C,f.return(e);case 3:h=y(f),J("wasm streaming compile failed: "+h),J("falling back to ArrayBuffer instantiation");case 2:return f.return(Ba(c,a))}})}function Da(a){for(;0<a.length;)a.shift()(F)}var Ea=[],Fa=[];function Ga(){var a=F.preRun.shift();Fa.push(a)}var Q=0,R=null;
function Ha(){Q++;var a,b;null==(b=(a=F).monitorRunDependencies)||b.call(a,Q)}function Ia(a){this.A=a-24}var Ja=0,Ka=0,La=[null,[],[]],Ma=globalThis.TextDecoder&&new TextDecoder;
function Na(a,b){b=void 0===b?0:b;var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Oa(a){return a?Na(L,a):""}
var Pa=[];F.print&&(wa=F.print);F.printErr&&(J=F.printErr);F.wasmBinary&&(K=F.wasmBinary);if(F.preInit)for("function"==typeof F.preInit&&(F.preInit=[F.preInit]);0<F.preInit.length;)F.preInit.shift()();
var Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab,N,bb={a:function(a,b,c){var d=new Ia(a);M[d.A+16>>2]=0;M[d.A+4>>2]=b;M[d.A+8>>2]=c;Ja=a;Ka++;throw Ja;},c:function(){return O("")},e:function(a,b){throw"Array index "+a+" out of bounds: [0,"+b+")";},d:function(a){var b=L.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-N.buffer.byteLength+65535)/65536|0;try{N.grow(d);za();var e=1;break a}catch(h){}e=
void 0}if(e)return!0}return!1},b:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var f=M[b>>2],k=M[b+4>>2];b+=8;for(var m=0;m<k;m++){var p=a,r=L[f+m],C=La[p];0===r||10===r?((1===p?wa:J)(Na(C)),C.length=0):C.push(r)}e+=k}M[d>>2]=e;return 0}};
function cb(){function a(){F.calledRun=!0;if(!xa){Da(Pa);db.g();var b,c;null==(c=(b=F).onRuntimeInitialized)||c.call(b);if(F.postRun)for("function"==typeof F.postRun&&(F.postRun=[F.postRun]);F.postRun.length;)b=F.postRun.shift(),Ea.push(b);Da(Ea)}}if(0<Q)R=cb;else{if(F.preRun)for("function"==typeof F.preRun&&(F.preRun=[F.preRun]);F.preRun.length;)Ga();Da(Fa);0<Q?R=cb:F.setStatus?(F.setStatus("Running..."),setTimeout(function(){setTimeout(function(){return F.setStatus("")},1);a()},1)):a()}}var db;
(function(){function a(e){e=db=e.exports;F._webidl_free=e.h;F._webidl_malloc=e.i;Qa=F._emscripten_bind_Language_getLanguageCode_0=e.j;Ra=F._emscripten_bind_Language___destroy___0=e.k;Sa=F._emscripten_bind_VoidPtr___destroy___0=e.l;Ta=F._emscripten_bind_LanguageGuess_getPercent_0=e.m;Ua=F._emscripten_bind_LanguageGuess_getLanguageCode_0=e.n;Va=F._emscripten_bind_LanguageGuess___destroy___0=e.o;Wa=F._emscripten_bind_LanguageInfo_detectLanguage_2=e.p;Xa=F._emscripten_bind_LanguageInfo_detectLanguage_5=
e.q;Ya=F._emscripten_bind_LanguageInfo_getIsReliable_0=e.r;Za=F._emscripten_bind_LanguageInfo_getLanguageCode_0=e.s;$a=F._emscripten_bind_LanguageInfo_get_languages_1=e.t;ab=F._emscripten_bind_LanguageInfo___destroy___0=e.u;N=e.f;za();Q--;var h,f;null==(f=(h=F).monitorRunDependencies)||f.call(h,Q);0==Q&&R&&(h=R,R=null,h());return db}var b,c,d;return D(function(e){if(1==e.v){Ha();b={a:bb};if(F.instantiateWasm)return e.return(new Promise(function(h){F.instantiateWasm(b,function(f,k){h(a(f,k))})}));
null!=P||(P=F.locateFile?F.locateFile("cld-worker.wasm",G):G+"cld-worker.wasm");return w(e,Ca(b),2)}c=e.C;d=a(c.instance);return e.return(d)})})();cb();function S(){}S.prototype=Object.create(S.prototype);S.prototype.constructor=S;S.prototype.I=S;S.K={};F.WrapperObject=S;function eb(a){return(a||S).K}F.getCache=eb;function T(a,b){var c=eb(b),d=c[a];if(d)return d;d=Object.create((b||S).prototype);d.A=a;return c[a]=d}F.wrapPointer=T;F.castObject=function(a,b){return T(a.A,b)};F.NULL=T(0);
F.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete eb(a.I)[a.A]};F.compare=function(a,b){return a.A===b.A};F.getPointer=function(a){return a.A};F.getClass=function(a){return a.I};
var U={buffer:0,size:0,M:0,R:[],L:0,S:function(){if(U.L){for(var a=0;a<U.R.length;a++)F._webidl_free(U.R[a]);U.R.length=0;F._webidl_free(U.buffer);U.buffer=0;U.size+=U.L;U.L=0}U.buffer||(U.size+=128,U.buffer=F._webidl_malloc(U.size),U.buffer||O());U.M=0},alloc:function(a,b){U.buffer||O();a=a.length*b.BYTES_PER_ELEMENT;a=8*Math.ceil(a/8);U.M+a>=U.size?(0<a||O(),U.L+=a,b=F._webidl_malloc(a),U.R.push(b)):(b=U.buffer+U.M,U.M+=a);return b}};
function fb(a){if("string"===typeof a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b=Array(b+1);d=b.length;c=0;if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var h=a.codePointAt(e);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|
h>>6&63;b[c++]=128|h&63;e++}}b[c]=0}a=U.alloc(b,ya);for(c=0;c<b.length;c++)ya[a+c]=b[c];return a}return a}function V(){throw"cannot construct a Language, no constructor in IDL";}V.prototype=Object.create(S.prototype);V.prototype.constructor=V;V.prototype.I=V;V.K={};F.Language=V;V.prototype.getLanguageCode=V.prototype.P=function(){return Oa(Qa(this.A))};V.prototype.__destroy__=function(){Ra(this.A)};function W(){throw"cannot construct a VoidPtr, no constructor in IDL";}W.prototype=Object.create(S.prototype);
W.prototype.constructor=W;W.prototype.I=W;W.K={};F.VoidPtr=W;W.prototype.__destroy__=function(){Sa(this.A)};function X(){throw"cannot construct a LanguageGuess, no constructor in IDL";}X.prototype=Object.create(V.prototype);X.prototype.constructor=X;X.prototype.I=X;X.K={};F.LanguageGuess=X;X.prototype.getPercent=X.prototype.da=function(){return Ta(this.A)};X.prototype.getLanguageCode=X.prototype.P=function(){return Oa(Ua(this.A))};X.prototype.__destroy__=function(){Va(this.A)};
function Y(){throw"cannot construct a LanguageInfo, no constructor in IDL";}Y.prototype=Object.create(V.prototype);Y.prototype.constructor=Y;Y.prototype.I=Y;Y.K={};F.LanguageInfo=Y;
Y.prototype.detectLanguage=Y.prototype.O=function(a,b,c,d,e){U.S();a=a&&"object"===typeof a?a.A:fb(a);b&&"object"===typeof b&&(b=b.A);c=c&&"object"===typeof c?c.A:fb(c);d&&"object"===typeof d&&(d=d.A);e=e&&"object"===typeof e?e.A:fb(e);return void 0===c?T(Wa(a,b),Y):void 0===d?T(_emscripten_bind_LanguageInfo_detectLanguage_3(a,b,c),Y):void 0===e?T(_emscripten_bind_LanguageInfo_detectLanguage_4(a,b,c,d),Y):T(Xa(a,b,c,d,e),Y)};Y.prototype.getIsReliable=Y.prototype.ba=function(){return!!Ya(this.A)};
Y.prototype.getLanguageCode=Y.prototype.P=function(){return Oa(Za(this.A))};Y.prototype.get_languages=Y.prototype.U=function(a){var b=this.A;a&&"object"===typeof a&&(a=a.A);return T($a(b,a),X)};Object.defineProperty(Y.prototype,"languages",{get:Y.prototype.U});Y.prototype.__destroy__=function(){ab(this.A)};Y.O=Y.prototype.O;U.alloc=U.alloc.bind(U);U.S=U.S.bind(U);
for(var Z={ISO_8859_1:0,ISO_8859_2:1,ISO_8859_3:2,ISO_8859_4:3,ISO_8859_5:4,ISO_8859_6:5,ISO_8859_7:6,ISO_8859_8:7,ISO_8859_9:8,ISO_8859_10:9,JAPANESE_EUC_JP:10,EUC_JP:10,JAPANESE_SHIFT_JIS:11,SHIFT_JIS:11,JAPANESE_JIS:12,JIS:12,CHINESE_BIG5:13,BIG5:13,CHINESE_GB:14,CHINESE_EUC_CN:15,EUC_CN:15,KOREAN_EUC_KR:16,EUC_KR:16,UNICODE_UNUSED:17,CHINESE_EUC_DEC:18,EUC_DEC:18,CHINESE_CNS:19,CNS:19,CHINESE_BIG5_CP950:20,BIG5_CP950:20,JAPANESE_CP932:21,CP932:21,UTF8:22,UNKNOWN_ENCODING:23,ASCII_7BIT:24,RUSSIAN_KOI8_R:25,
KOI8_R:25,RUSSIAN_CP1251:26,CP1251:26,MSFT_CP1252:27,CP1252:27,RUSSIAN_KOI8_RU:28,KOI8_RU:28,MSFT_CP1250:29,CP1250:29,ISO_8859_15:30,MSFT_CP1254:31,CP1254:31,MSFT_CP1257:32,CP1257:32,ISO_8859_11:33,MSFT_CP874:34,CP874:34,MSFT_CP1256:35,CP1256:35,MSFT_CP1255:36,CP1255:36,ISO_8859_8_I:37,HEBREW_VISUAL:38,CZECH_CP852:39,CP852:39,CZECH_CSN_369103:40,CSN_369103:40,MSFT_CP1253:41,CP1253:41,RUSSIAN_CP866:42,CP866:42,ISO_8859_13:43,ISO_2022_KR:44,GBK:45,GB18030:46,BIG5_HKSCS:47,ISO_2022_CN:48,TSCII:49,TAMIL_MONO:50,
TAMIL_BI:51,JAGRAN:52,MACINTOSH_ROMAN:53,UTF7:54,BHASKAR:55,HTCHANAKYA:56,UTF16BE:57,UTF16LE:58,UTF32BE:59,UTF32LE:60,BINARYENC:61,HZ_GB_2312:62,UTF8UTF8:63,TAM_ELANGO:64,TAM_LTTMBARANI:65,TAM_SHREE:66,TAM_TBOOMIS:67,TAM_TMNEWS:68,TAM_WEBTAMIL:69,KDDI_SHIFT_JIS:70,DOCOMO_SHIFT_JIS:71,SOFTBANK_SHIFT_JIS:72,KDDI_ISO_2022_JP:73,ISO_2022_JP:73,SOFTBANK_ISO_2022_JP:74},gb=g(Object.keys(Z)),hb=gb.next();!hb.done;hb=gb.next()){var ib=hb.value;ib.includes("_")&&(Z[ib.replace(/_/g,"")]=Z[ib])}
F.onRuntimeInitialized=function(){onmessage=function(a){a=a.data;if(void 0==a.tld&&void 0==a.encoding&&void 0==a.language)var b=Y.O(a.text,!a.isHTML);else{var c=String(a.encoding).toUpperCase().replace(/[_-]/g,"");c=Z.hasOwnProperty(c)?Z[c]:Z.UNKNOWN_ENCODING;b=Y.O(a.text,!a.isHTML,a.tld||null,c,a.language||null)}postMessage({language:b.P(),confident:b.ba(),languages:Array(3).fill(0).map(function(d,e){d=b.U(e);return{languageCode:d.P(),percent:d.da()}}).filter(function(d){return"un"!=d.languageCode||
0<d.percent})});F.destroy(b)};postMessage("ready")};
